In [1]:
import numpy as np

lst = [1, 2, 3, 4, 5]
print(lst * 2)  # This will concatenate the list with itself
my_list = list(map(lambda x: x * 2, lst))
print(my_list)

arr = np.array(lst)
print(arr * 2)  # This will multiply each element by 2


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


# Multidimensional Arrays

In [2]:
dim0 = np.array(100)
dim1 = np.array([1, 2, 3])
dim2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
dim3 = np.array([
    [
        ['A', 'B', 'C'],
        ['D', 'E', 'F']
    ],
    
    [
        ['G', 'H', 'I'],
        ['J', 'K', 'L']
    ]
])

print('Number of dimensions and shape of each array:')
print(dim0.ndim, 'and', dim0.shape)
print(dim1.ndim, 'and', dim1.shape)
print(dim2.ndim, 'and', dim2.shape)
print(dim3.ndim, 'and', dim3.shape, '\n')

# Indexing
print('Indexing examples:')
print('dim1[0]:', dim1[0])
print('dim1[1]:', dim1[1])
print('dim2[0, 2]:', dim2[0, 2])
print('dim2[1, 1]:', dim2[1, 1])
print('dim2[2, 0]:', dim2[2, 0])
word = dim3[1, 1, 1] + dim3[0, 0, 0] + dim3[1, 0, 1] + dim3[0, 1, 2]
print(word)


Number of dimensions and shape of each array:
0 and ()
1 and (3,)
2 and (3, 3)
3 and (2, 2, 3) 

Indexing examples:
dim1[0]: 1
dim1[1]: 2
dim2[0, 2]: 3
dim2[1, 1]: 5
dim2[2, 0]: 7
KAHF


# Slicing

In [ ]:
array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
print('Slicing examples:')
print(array[0], '\n')
print(array[1:3], '\n')
print(array[::-1], '\n')
print(array[1::-2], '\n')

print(array[:, -1], '\n')
print(array[:, :2], '\n')
print(array[:, ::-1], '\n')

print(array[::2, :-1], '\n')
print(array[:2:-1, ::-2], '\n')
print(array[1:3, 1:3], '\n')

Slicing examples:
[1 2 3] 

[[4 5 6]
 [7 8 9]] 

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]] 

[[4 5 6]] 

[ 3  6  9 12] 

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]] 

[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]] 

[[1 2]
 [7 8]] 

[] 



# Arithmetic

In [16]:
# Scalar operations
print('Scalar operations:')
print(dim1 + 5)
print(dim1 - 3)
print(dim1 * 6)
print(dim1 / 2)
print(dim1 ** 3, '\n')

# Vectorized Mathematical Operations
print('Vectorized mathematical operations:')
aaa = np.array([1, 2, 3])
print(np.sqrt(aaa))
print(np.exp(aaa))
bbb = np.array([2.1, 3.5, 4.0])
print(np.round(bbb))
print(np.floor(bbb))
print(np.ceil(bbb))
print(np.pi)
print('Area of circle:')
print(np.pi * dim1 ** 2, '\n')

# Element-wise operations
print('Element-wise operations:')
print(dim2[0] + dim2[1])
print(dim2[0] - dim2[2])
print(dim2[1] * dim2[2])
print(dim2[2] / dim2[0])
print(dim2[2] ** dim2[1], '\n')

# Comparison operations
print('Comparison operations:')
scores = np.array([85, 92, 78, 90, 88])
print(scores > 30)
print(scores < 80)
scores[scores < 80] = 80
print(scores)

Scalar operations:
[6 7 8]
[-2 -1  0]
[ 6 12 18]
[0.5 1.  1.5]
[ 1  8 27] 

Vectorized mathematical operations:
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 4.]
[2. 3. 4.]
[3. 4. 4.]
3.141592653589793
Area of circle:
[ 3.14159265 12.56637061 28.27433388] 

Element-wise operations:
[5 7 9]
[-6 -6 -6]
[28 40 54]
[7. 4. 3.]
[  2401  32768 531441] 

Comparison operations:
[ True  True  True  True  True]
[False False  True False False]
[85 92 80 90 88]
