In [2]:
import numpy as np

lst = [1, 2, 3, 4, 5]
print(lst * 2)  # This will concatenate the list with itself
my_list = list(map(lambda x: x * 2, lst))
print(my_list)

arr = np.array(lst)
print(arr * 2)  # This will multiply each element by 2


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


# Multidimensional Arrays

In [3]:
dim0 = np.array(100)
dim1 = np.array([1, 2, 3])
dim2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
dim3 = np.array([
    [
        ['A', 'B', 'C'],
        ['D', 'E', 'F']
    ],
    
    [
        ['G', 'H', 'I'],
        ['J', 'K', 'L']
    ]
])

print('Number of dimensions and shape of each array:')
print(dim0.ndim, 'and', dim0.shape)
print(dim1.ndim, 'and', dim1.shape)
print(dim2.ndim, 'and', dim2.shape)
print(dim3.ndim, 'and', dim3.shape, '\n')

# Indexing
print('Indexing examples:')
print('dim1[0]:', dim1[0])
print('dim1[1]:', dim1[1])
print('dim2[0, 2]:', dim2[0, 2])
print('dim2[1, 1]:', dim2[1, 1])
print('dim2[2, 0]:', dim2[2, 0])
word = dim3[1, 1, 1] + dim3[0, 0, 0] + dim3[1, 0, 1] + dim3[0, 1, 2]
print(word)


Number of dimensions and shape of each array:
0 and ()
1 and (3,)
2 and (3, 3)
3 and (2, 2, 3) 

Indexing examples:
dim1[0]: 1
dim1[1]: 2
dim2[0, 2]: 3
dim2[1, 1]: 5
dim2[2, 0]: 7
KAHF


# Slicing

In [4]:
array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
print('Slicing examples:')
print(array[0], '\n')
print(array[1:3], '\n')
print(array[::-1], '\n')
print(array[1::-2], '\n')

print(array[:, -1], '\n')
print(array[:, :2], '\n')
print(array[:, ::-1], '\n')

print(array[::2, :-1], '\n')
print(array[:2:-1, ::-2], '\n')
print(array[1:3, 1:3], '\n')

Slicing examples:
[1 2 3] 

[[4 5 6]
 [7 8 9]] 

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]] 

[[4 5 6]] 

[ 3  6  9 12] 

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]] 

[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]] 

[[1 2]
 [7 8]] 

[[12 10]] 

[[5 6]
 [8 9]] 



# Arithmetic

In [5]:
# Scalar operations
print('Scalar operations:')
print(dim1 + 5)
print(dim1 - 3)
print(dim1 * 6)
print(dim1 / 2)
print(dim1 ** 3, '\n')

# Vectorized Mathematical Operations
print('Vectorized mathematical operations:')
aaa = np.array([1, 2, 3])
print(np.sqrt(aaa))
print(np.exp(aaa))
bbb = np.array([2.1, 3.5, 4.0])
print(np.round(bbb))
print(np.floor(bbb))
print(np.ceil(bbb))
print(np.pi)
print('Area of circle:')
print(np.pi * dim1 ** 2, '\n')

# Element-wise operations
print('Element-wise operations:')
print(dim2[0] + dim2[1])
print(dim2[0] - dim2[2])
print(dim2[1] * dim2[2])
print(dim2[2] / dim2[0])
print(dim2[2] ** dim2[1], '\n')

# Comparison operations
print('Comparison operations:')
scores = np.array([85, 92, 78, 90, 88])
print(scores > 30)
print(scores < 80)
scores[scores < 80] = 80
print(scores)

Scalar operations:
[6 7 8]
[-2 -1  0]
[ 6 12 18]
[0.5 1.  1.5]
[ 1  8 27] 

Vectorized mathematical operations:
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 4.]
[2. 3. 4.]
[3. 4. 4.]
3.141592653589793
Area of circle:
[ 3.14159265 12.56637061 28.27433388] 

Element-wise operations:
[5 7 9]
[-6 -6 -6]
[28 40 54]
[7. 4. 3.]
[  2401  32768 531441] 

Comparison operations:
[ True  True  True  True  True]
[False False  True False False]
[85 92 80 90 88]


# Broadcasting

Broadcasting is a powerful mechanism in NumPy that allows operations to be performed on arrays of different shapes.
When performing an operation between two arrays, NumPy compares their shapes and applies the operation according to
certain rules. If the shapes are compatible, NumPy will automatically "broadcast" the smaller array across the
larger one so that they have compatible shapes for element-wise operations

The rules for broadcasting are as follows:
1. If the arrays have different numbers of dimensions, the shape of the smaller array is padded
    with ones on its leading (left) side until both shapes have the same number of dimensions.
2. If the shape of the arrays does not match in any dimension, the array with shape equal to 1 in that dimension is
    stretched to match the other shape.

In [6]:
AA = np.array([
    [1, 2, 3, 4]
])
BB = np.array([
    [5], [6], [7], [8]
])
print(AA.shape)
print(BB.shape)
print('Broadcasting example:')
print(AA + BB)

(1, 4)
(4, 1)
Broadcasting example:
[[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]]


# Aggregate Functions

In [7]:
data = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])
print('Statistical functions:')
print(np.sum(data))
print(np.mean(data))
print(np.std(data))
print(np.var(data))
print(np.min(data))
print(np.max(data))
print(np.argmin(data))
print(np.argmax(data))
print(np.median(data))
print(np.percentile(data, 25))
print(np.percentile(data, 75))
print('Sum of each column:', np.sum(data, axis=0))
print('Sum of each row:', np.sum(data, axis=1))


Statistical functions:
120
8.0
4.320493798938574
18.666666666666668
1
15
0
14
8.0
4.5
11.5
Sum of each column: [18 21 24 27 30]
Sum of each row: [15 40 65]


# Filtering

In [12]:
ages = np.array([
    [24, 30, 22],
    [28, 26, 31],
    [12, 23, 65],
    [78, 45, 67]
])

teenagers = ages[ages < 18]
adults = np.where((ages >= 18) & (ages < 65), ages, 0)
senior = ages[ages >= 65]
evens = ages[ages % 2 == 0]
odds = ages[ages % 2 == 1]
print('Filtering examples:')
print('Teenagers:', teenagers)
print('Adults:', adults)
print('Senior:', senior)
print('Even ages:', evens)
print('Odd ages:', odds)



Filtering examples:
Teenagers: [12]
Adults: [[24 30 22]
 [28 26 31]
 [ 0 23  0]
 [ 0 45  0]]
Senior: [65 78 67]
Even ages: [24 30 22 28 26 12 78]
Odd ages: [31 23 65 45 67]


# Random Number

In [44]:
rng = np.random.default_rng()
print(rng.integers(low=1, high=21))
print(rng.integers(low=1, high=21, size=(3, 4)), '\n')


print(np.random.uniform(low=0.0, high=1.0))
print(np.random.uniform(low=0.0, high=1.0, size=(3, 3)), '\n')

CC = np.array([1, 2, 3, 4, 5, 6, 7])
rng.shuffle(CC)
print('Shuffled array:', CC, '\n')

fruits = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])
fruit = rng.choice(fruits, size=3, replace=False)
print('Randomly selected fruits:', fruit)

1
[[15  1  3 12]
 [10  2  9 17]
 [ 2 14 18 17]] 

0.5904336763748508
[[0.81543446 0.42982633 0.48103238]
 [0.46113468 0.21435991 0.70101456]
 [0.67721579 0.0707112  0.59745186]] 

Shuffled array: [6 2 5 1 4 7 3] 

Randomly selected fruits: ['date' 'elderberry' 'apple']
